inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  CacheRootDirectory: tmp

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/requests/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - Rakefile
    - Guardfile
    - lib/tasks/**/*.rb
    - lib/tasks/*.rake
    - config/**/*.rb

Lint/MissingSuper:
  Exclude:
    - app/services/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb
    - spec/views/**/*.rb

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*.rb
    - spec/views/**/*.rb

RSpec/MessageSpies:
  EnforcedStyle: receive